name: CI-CD

on:
  push:
    branches: ["main"]
    paths:
      - "src/***" # Apenas alterações na pasta src
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v4.2.2
        
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildando a Imagem Docker e Efetuando o Push 
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            dellabeneta/fake-shop:latest
            dellabeneta/fake-shop:v${{ github.run_number}}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Obtendo o código da aplicação
        uses: actions/checkout@v4.2.2

      - name: Obtendo o kubeconfig e setando o contexto
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}   

      - name: Aplicando o Deployment e o Service
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          namespace: default